;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-left-brace
        TeX-insert-backslash
        asm-comment
        beginning-of-visual-line
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        end-of-visual-line
        eval-last-sexp
        indent-for-tab-command
        keyboard-escape-quit
        kmacro-end-or-call-macro
        org-cycle
        org-deadline
        org-force-self-insert
        org-self-insert-command
        org-shiftdown
        ))

(setq mc/cmds-to-run-once
      '(
        handle-switch-frame
        sgml-slash
        ))
